// GENERATED CODE - DO NOT MODIFY BY HAND
// dart format width=80

// **************************************************************************
// MCPGenerator
// **************************************************************************

// ignore_for_file: type=lint
part of 'modern_capabilities.dart';

/// Generated extension for [ModernCapabilitiesServer] that provides automatic registration
/// of all annotated MCP tools, resources, and prompts.
///
/// This code is automatically generated by the MCP Dart framework.
/// Do not modify this file directly - instead, modify the source
/// class and run `dart run build_runner build` to regenerate.
extension ModernCapabilitiesServerRegistration on ModernCapabilitiesServer {
  /// Registers all generated handlers for annotated methods.
  /// Call this method in your constructor to automatically register
  /// all MCP tools, resources, and prompts.
  void registerGeneratedHandlers() {
    // Register handler for @MCPCompletion('classify')

    registerPromptCompletion('classify', (request) async {
      return await completeClassifyPrompt(request);
    });

    // Register handler for @MCPTool('log_demo')

    registerTool(
      'log_demo',
      (context) async {
        final message = context.param<String>('message');
        return await logDemo(message);
      },
      description:
          'Emit a few structured log notifications and return a summary.',
      inputSchema: {
        'type': 'object',
        'properties': {
          'message': {
            'type': 'string',
            'description': 'Message to include in the logs',
          },
        },
        'required': ['message'],
      },
    );

    // Register handler for @MCPTool('long_running_echo')

    registerTool(
      'long_running_echo',
      (context) async {
        final text = context.param<String>('text');
        final delayMs = context.param<int>('delayMs');
        return await longRunningEcho(text, delayMs);
      },
      description: 'Return text after a short delay. Works well with tasks.',
      annotations: MCPToolAnnotations(taskSupport: 'optional'),
      inputSchema: {
        'type': 'object',
        'properties': {
          'text': {'type': 'string', 'description': 'Text to echo back'},
          'delayMs': {
            'type': 'integer',
            'description': 'Delay in milliseconds',
          },
        },
        'required': ['text', 'delayMs'],
      },
    );

    // Register handler for @MCPResource('example-status')

    registerResource('example-status', (uri) async {
      final result = await exampleStatus();
      return MCPResourceContent(
        uri: uri,
        name: 'example-status',
        mimeType: 'application/json',
        text: jsonEncode(result),
      );
    });

    // Register handler for @MCPPrompt('classify')

    registerPrompt('classify', (args) {
      final category = args['category'] as String;
      final text = args['text'] as String;
      return classifyPrompt(category, text);
    });
  }

  /// Generates standardized usage documentation for MCP servers.
  ///
  /// This helper method provides consistent help text formatting
  /// for this specific MCP server with its available capabilities.
  void showUsage({String? serverName}) {
    print('Usage: dart ${serverName ?? "server"}.dart [options]');
    print('');
    print('Options:');
    print('  --stdio        Start server in stdio mode (default)');
    print('  --http         Start HTTP server on port 8080');
    print('  --port <port>  Specify HTTP port (default: 8080)');
    print('  --help, -h     Show this help message');
    print('');
    print('Available tools: log_demo, long_running_echo');
    print('Available resources: example-status');
    print('Available prompts: classify');
    print('');

    print('Examples:');
    print('  dart ${serverName ?? "server"}.dart');
    print('  dart ${serverName ?? "server"}.dart --http');
    print('  dart ${serverName ?? "server"}.dart --http --port 3000');
  }
}
